# Generated by Django 5.2.4 on 2025-09-01 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nom_roll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nom_roll.personal'),
        ),
    ]
