# Generated by Django 5.2.6 on 2025-09-09 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nom_roll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topmanagement',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('birth_cert', 'Birth Certificate'), ('state_of_origin', 'State of Origin'), ('fslc', 'FSLC'), ('ssce', 'SSCE'), ('nce', 'NCE'), ('nd', 'ND'), ('hnd', 'HND'), ('bachelors', 'Bachelors'), ('nysc', 'NYSC'), ('pgd', 'PGD'), ('masters', 'MASTERS'), ('doctorate', 'PhD'), ('professional', 'Professional'), ('other', 'Other'), ('employment', 'Employment Letter'), ('promotion', 'Promotion'), ('query', 'Query'), ('leave_approval', 'Leave approval'), ('leave_resumption', 'Leave resumption')], max_length=24)),
                ('file', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='nom_roll.employee')),
            ],
        ),
    ]
