# Generated by Django 5.2.6 on 2025-09-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nom_roll', '0002_remove_topmanagement_user_employee_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='section',
            field=models.CharField(choices=[('administration', 'Administration'), ('clinicals', 'Clinical Services')], default='administration', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('administration', 'Administration'), ('clinicals', 'Clinical Services')], default='permanent', max_length=14),
        ),
    ]
