# Generated by Django 5.2.4 on 2025-08-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nom_roll', '0003_department_user_employee_id_employee_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='office_email',
            field=models.EmailField(max_length=254),
        ),
    ]
