# Generated by Django 5.2.4 on 2025-07-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfa', models.CharField(max_length=50)),
                ('pfa_no', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
