# Generated by Django 5.2.4 on 2025-07-11 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nom_roll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('conhess', models.IntegerField()),
                ('designation', models.CharField(max_length=30)),
                ('step', models.IntegerField()),
                ('dolp', models.DateField()),
                ('file_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nom_roll.employee')),
            ],
        ),
    ]
