# Generated by Django 5.2.4 on 2025-09-02 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nom_roll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('conhess', models.IntegerField()),
                ('designation', models.CharField(max_length=30)),
                ('step', models.IntegerField()),
                ('dolp', models.DateField()),
                ('file_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nom_roll.employee')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
