# Generated by Django 5.2.4 on 2025-07-11 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NHFDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField(default=2025)),
                ('nhf_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('standard_deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhf_records', to='fa.standarddeduction')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('standard_deduction', 'month', 'year')},
            },
        ),
    ]
