# Generated by Django 5.2.4 on 2025-07-11 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nom_roll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('task_name', models.CharField(max_length=30)),
                ('target', models.TextField()),
                ('result', models.TextField()),
                ('date', models.DateField()),
                ('file_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nom_roll.employee')),
            ],
        ),
    ]
