# Generated by Django 5.2.4 on 2025-09-01 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nom_roll', '0002_alter_employee_mobile_number'),
        ('tasks', '0002_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nom_roll.employee'),
        ),
    ]
