# Generated by Django 5.2.4 on 2025-07-11 01:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nom_roll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfa_name', models.CharField(max_length=30, unique=True)),
                ('pfa_code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('teaching_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('shift_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('clinical_rate', models.DecimalField(decimal_places=2, default=7.5, max_digits=5)),
                ('call_duty_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('specialist_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('is_clinical', models.BooleanField(default=False)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nom_roll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('paypoint', models.CharField(max_length=25)),
                ('salary_structure', models.CharField(max_length=10)),
                ('ippis_no', models.CharField(max_length=7, unique=True)),
                ('file_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nom_roll.employee')),
                ('pfa_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fa.pension')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_structure', models.CharField(choices=[('CONHESS', 'CONHESS'), ('CONMESS', 'CONMESS'), ('CONTOPSAL', 'CONTOPSAL')], max_length=10)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('step', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('annual_salary', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['salary_structure', 'level', 'step'],
                'unique_together': {('salary_structure', 'level', 'step')},
            },
        ),
        migrations.CreateModel(
            name='StandardDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhis', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('nhf', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('pension_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('ippis_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fa.account')),
            ],
        ),
    ]
