# Generated by Django 5.2.4 on 2025-09-01 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fa', '0002_pension_user_salarystructure_user_and_more'),
        ('nom_roll', '0002_alter_employee_mobile_number'),
        ('pension', '0002_alter_pension_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allowance',
            old_name='employee',
            new_name='file_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='employee',
        ),
        migrations.AlterField(
            model_name='account',
            name='file_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nom_roll.employee'),
        ),
        migrations.AlterField(
            model_name='account',
            name='pfa_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pension.pension'),
        ),
    ]
