# Generated by Django 5.2.4 on 2025-09-02 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nom_roll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadre_name', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
                ('designation', models.CharField(max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aper_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('civil_service_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('area_of_specialization_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('general_paper_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5)),
                ('isPromoted', models.BooleanField(default=True)),
                ('file_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nom_roll.employee')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('is_eligible', models.BooleanField(default=False)),
                ('checked_on', models.DateTimeField(auto_now=True)),
                ('file_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nom_roll.employee')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('file_number', 'year')},
            },
        ),
    ]
