# Generated by Django 5.2.4 on 2025-07-11 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nom_roll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAndDisc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=300)),
                ('file_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nom_roll.employee')),
            ],
        ),
    ]
