# Generated by Django 5.2.4 on 2025-07-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_attended', models.CharField(max_length=50)),
                ('strt_date', models.DateField()),
                ('end_date', models.DateField()),
                ('certificate_obtained', models.CharField(max_length=10, unique=True)),
                ('certificate_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuing_body', models.CharField(max_length=100)),
                ('certificate_id', models.CharField(max_length=20, unique=True)),
                ('certificate_name', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('licence_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
