# Generated by Django 5.2.4 on 2025-07-13 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=15)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('ippis_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fa.account')),
            ],
        ),
    ]
