# Generated by Django 5.2.4 on 2025-09-01 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_alter_archive_user'),
        ('fa', '0002_pension_user_salarystructure_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='ippis_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fa.account'),
        ),
    ]
