# Generated by Django 5.2.4 on 2025-09-02 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30)),
                ('task_id', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('target', models.TextField()),
                ('outcome', models.TextField()),
                ('rating', models.CharField(max_length=10)),
                ('ippis_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fa.account')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
