# Generated by Django 5.2.4 on 2025-07-11 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fa', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('target', models.TextField()),
                ('outcome', models.TextField()),
                ('rating', models.CharField(max_length=10)),
                ('ippis_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fa.account')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
