# Generated by Django 5.2.4 on 2025-07-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='task',
            new_name='task_name',
        ),
    ]
