# Generated by Django 5.2.4 on 2025-09-01 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fa', '0003_rename_employee_allowance_file_number_and_more'),
        ('performance', '0002_alter_performance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='ippis_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fa.account'),
        ),
    ]
