# Generated by Django 5.2.4 on 2025-08-11 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_rename_task_performance_task_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='performance',
            name='ippis_no',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='performance',
            name='task_id',
            field=models.IntegerField(),
        ),
    ]
