# Generated by Django 5.2.4 on 2025-07-12 21:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fa', '0001_initial'),
        ('nom_roll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerDescending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_year', models.DateField()),
                ('previous_designation', models.CharField(max_length=30)),
                ('current_designation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveDescending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('nature_of_leave', models.CharField(max_length=50)),
                ('resumption', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuing_body', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('license_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QualificationsDescending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.DateField()),
                ('finish', models.DateField()),
                ('certificate_obtained', models.CharField(max_length=10)),
                ('certificate_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=30)),
                ('grade_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('conhess', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('dofa', models.DateField()),
                ('dolp', models.DateField()),
                ('edor', models.DateField()),
                ('file_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nom_roll.employee')),
                ('ippis_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fa.account')),
            ],
        ),
    ]
