# Generated by Django 5.2.4 on 2025-07-10 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nom_roll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nhis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('relationship', models.CharField(choices=[('Spouse', 'Spouse'), ('Child', 'Child'), ('Parent', 'Parent'), ('Other', 'Other')], max_length=10)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nom_roll.personal', to_field='email')),
            ],
        ),
    ]
