# Generated by Django 5.2.4 on 2025-09-01 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhis', '0002_alter_nhis_user'),
        ('nom_roll', '0002_alter_employee_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhis',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nom_roll.personal'),
        ),
    ]
